<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('settings', function (Blueprint $table) {
            $table->integer('settings_id')->primary();
            $table->timestamp('settings_created');
            $table->timestamp('settings_updated');
            $table->string('settings_type', 50)->nullable()->default('standalone');
            $table->integer('settings_saas_tenant_id')->nullable();
            $table->string('settings_saas_status', 100)->nullable();
            $table->integer('settings_saas_package_id')->nullable();
            $table->string('settings_saas_onetimelogin_key', 100)->nullable();
            $table->string('settings_saas_onetimelogin_destination', 100)->nullable();
            $table->integer('settings_saas_package_limits_clients')->nullable();
            $table->integer('settings_saas_package_limits_team')->nullable();
            $table->integer('settings_saas_package_limits_projects')->nullable();
            $table->text('settings_saas_notification_uniqueid')->nullable();
            $table->text('settings_saas_notification_body')->nullable();
            $table->text('settings_saas_notification_read')->nullable();
            $table->text('settings_saas_notification_action')->nullable();
            $table->text('settings_saas_notification_action_url')->nullable();
            $table->string('settings_saas_email_server_type', 30)->nullable()->default('local');
            $table->text('settings_saas_email_forwarding_address')->nullable();
            $table->text('settings_saas_email_local_address')->nullable();
            $table->timestamp('settings_installation_date');
            $table->text('settings_version');
            $table->text('settings_purchase_code')->nullable();
            $table->text('settings_company_name')->nullable();
            $table->text('settings_company_address_line_1')->nullable();
            $table->text('settings_company_state')->nullable();
            $table->text('settings_company_city')->nullable();
            $table->text('settings_company_zipcode')->nullable();
            $table->text('settings_company_country')->nullable();
            $table->text('settings_company_telephone')->nullable();
            $table->text('settings_company_customfield_1')->nullable();
            $table->text('settings_company_customfield_2')->nullable();
            $table->text('settings_company_customfield_3')->nullable();
            $table->text('settings_company_customfield_4')->nullable();
            $table->text('settings_clients_registration')->nullable();
            $table->text('settings_clients_shipping_address')->nullable();
            $table->string('settings_clients_disable_email_delivery', 12)->nullable()->default('disabled');
            $table->string('settings_clients_app_login', 12)->nullable()->default('enabled');
            $table->string('settings_customfields_display_leads', 12)->nullable()->default('toggled');
            $table->string('settings_customfields_display_clients', 12)->nullable()->default('toggled');
            $table->string('settings_customfields_display_projects', 12)->nullable()->default('toggled');
            $table->string('settings_customfields_display_tasks', 12)->nullable()->default('toggled');
            $table->string('settings_customfields_display_tickets', 12)->nullable()->default('toggled');
            $table->text('settings_email_general_variables')->nullable();
            $table->text('settings_email_from_address')->nullable();
            $table->text('settings_email_from_name')->nullable();
            $table->text('settings_email_server_type')->nullable();
            $table->text('settings_email_smtp_host')->nullable();
            $table->text('settings_email_smtp_port')->nullable();
            $table->text('settings_email_smtp_username')->nullable();
            $table->text('settings_email_smtp_password')->nullable();
            $table->text('settings_email_smtp_encryption')->nullable();
            $table->text('settings_estimates_default_terms_conditions')->nullable();
            $table->text('settings_estimates_prefix')->nullable();
            $table->string('settings_estimates_show_view_status', 10)->nullable()->default('yes');
            $table->string('settings_modules_projects', 10)->nullable()->default('enabled');
            $table->string('settings_modules_tasks', 10)->nullable()->default('enabled');
            $table->string('settings_modules_invoices', 10)->nullable()->default('enabled');
            $table->string('settings_modules_payments', 10)->nullable()->default('enabled');
            $table->string('settings_modules_leads', 10)->nullable()->default('enabled');
            $table->string('settings_modules_knowledgebase', 10)->nullable()->default('enabled');
            $table->string('settings_modules_estimates', 10)->nullable()->default('enabled');
            $table->string('settings_modules_expenses', 10)->nullable()->default('enabled');
            $table->string('settings_modules_notes', 10)->nullable()->default('enabled');
            $table->string('settings_modules_subscriptions', 10)->nullable()->default('enabled');
            $table->string('settings_modules_contracts', 10)->nullable()->default('enabled');
            $table->string('settings_modules_proposals', 10)->nullable()->default('enabled');
            $table->string('settings_modules_tickets', 10)->nullable()->default('enabled');
            $table->string('settings_modules_timetracking', 10)->nullable()->default('enabled');
            $table->string('settings_modules_reminders', 10)->nullable()->default('enabled');
            $table->string('settings_modules_spaces', 10)->nullable()->default('enabled');
            $table->string('settings_modules_messages', 10)->nullable()->default('enabled');
            $table->text('settings_modules_reports')->nullable();
            $table->text('settings_modules_calendar')->nullable();
            $table->integer('settings_files_max_size_mb')->nullable()->default(300);
            $table->string('settings_knowledgebase_article_ordering', 40)->nullable()->default('name');
            $table->string('settings_knowledgebase_allow_guest_viewing', 10)->nullable()->default('no');
            $table->text('settings_knowledgebase_external_pre_body')->nullable();
            $table->text('settings_knowledgebase_external_post_body')->nullable();
            $table->text('settings_knowledgebase_external_header')->nullable();
            $table->text('settings_system_timezone')->nullable();
            $table->text('settings_system_date_format')->nullable();
            $table->text('settings_system_datepicker_format')->nullable();
            $table->text('settings_system_default_leftmenu')->nullable();
            $table->text('settings_system_default_statspanel')->nullable();
            $table->smallInteger('settings_system_pagination_limits')->nullable();
            $table->smallInteger('settings_system_kanban_pagination_limits')->nullable();
            $table->text('settings_system_currency_code')->nullable();
            $table->text('settings_system_currency_symbol')->nullable();
            $table->text('settings_system_currency_position')->nullable();
            $table->text('settings_system_currency_hide_decimal')->nullable();
            $table->text('settings_system_decimal_separator')->nullable();
            $table->text('settings_system_thousand_separator')->nullable();
            $table->string('settings_system_close_modals_body_click', 10)->nullable()->default('no');
            $table->string('settings_system_language_default', 40)->nullable()->default('en');
            $table->string('settings_system_language_allow_users_to_change', 10)->nullable()->default('yes');
            $table->string('settings_system_logo_large_name', 40)->nullable()->default('logo.jpg');
            $table->string('settings_system_logo_small_name', 40)->nullable()->default('logo-small.jpg');
            $table->string('settings_system_logo_versioning', 40)->nullable()->default('1');
            $table->string('settings_system_session_login_popup', 10)->nullable()->default('disabled');
            $table->date('settings_system_javascript_versioning')->nullable();
            $table->string('settings_system_exporting_strip_html', 10)->nullable()->default('yes');
            $table->string('settings_tags_allow_users_create', 10)->nullable()->default('yes');
            $table->string('settings_leads_allow_private', 10)->nullable()->default('yes');
            $table->string('settings_leads_allow_new_sources', 10)->nullable()->default('yes');
            $table->text('settings_leads_kanban_value')->nullable();
            $table->text('settings_leads_kanban_date_created')->nullable();
            $table->text('settings_leads_kanban_category')->nullable();
            $table->text('settings_leads_kanban_date_contacted')->nullable();
            $table->text('settings_leads_kanban_telephone')->nullable();
            $table->text('settings_leads_kanban_source')->nullable();
            $table->text('settings_leads_kanban_email')->nullable();
            $table->text('settings_leads_kanban_tags')->nullable();
            $table->text('settings_leads_kanban_reminder')->nullable();
            $table->text('settings_tasks_client_visibility')->nullable();
            $table->text('settings_tasks_billable')->nullable();
            $table->text('settings_tasks_kanban_date_created')->nullable();
            $table->text('settings_tasks_kanban_date_due')->nullable();
            $table->text('settings_tasks_kanban_date_start')->nullable();
            $table->text('settings_tasks_kanban_priority')->nullable();
            $table->text('settings_tasks_kanban_milestone')->nullable();
            $table->text('settings_tasks_kanban_client_visibility')->nullable();
            $table->string('settings_tasks_kanban_project_title', 10)->nullable()->default('show');
            $table->string('settings_tasks_kanban_client_name', 10)->nullable()->default('show');
            $table->text('settings_tasks_kanban_tags')->nullable();
            $table->text('settings_tasks_kanban_reminder')->nullable();
            $table->string('settings_tasks_send_overdue_reminder', 10)->nullable()->default('yes');
            $table->text('settings_invoices_prefix')->nullable();
            $table->smallInteger('settings_invoices_recurring_grace_period')->nullable();
            $table->text('settings_invoices_default_terms_conditions')->nullable();
            $table->text('settings_invoices_show_view_status');
            $table->text('settings_invoices_show_project_on_invoice');
            $table->string('settings_projects_cover_images', 10)->nullable()->default('disabled');
            $table->string('settings_projects_permissions_basis', 40)->nullable()->default('user_roles');
            $table->string('settings_projects_categories_main_menu', 10)->nullable()->default('no');
            $table->decimal('settings_projects_default_hourly_rate', 10)->nullable()->default(0);
            $table->text('settings_projects_allow_setting_permission_on_project_creation')->nullable();
            $table->text('settings_projects_clientperm_files_view')->nullable();
            $table->text('settings_projects_clientperm_files_upload')->nullable();
            $table->text('settings_projects_clientperm_comments_view')->nullable();
            $table->text('settings_projects_clientperm_comments_post')->nullable();
            $table->text('settings_projects_clientperm_tasks_view')->nullable();
            $table->text('settings_projects_clientperm_tasks_collaborate')->nullable();
            $table->text('settings_projects_clientperm_tasks_create')->nullable();
            $table->text('settings_projects_clientperm_timesheets_view')->nullable();
            $table->text('settings_projects_clientperm_expenses_view')->nullable();
            $table->text('settings_projects_clientperm_milestones_view')->nullable();
            $table->text('settings_projects_clientperm_assigned_view')->nullable();
            $table->text('settings_projects_assignedperm_milestone_manage')->nullable();
            $table->text('settings_projects_assignedperm_tasks_collaborate')->nullable();
            $table->text('settings_projects_events_show_task_status_change')->nullable();
            $table->text('settings_stripe_secret_key')->nullable();
            $table->text('settings_stripe_public_key')->nullable();
            $table->text('settings_stripe_webhooks_key')->nullable();
            $table->text('settings_stripe_default_subscription_plan_id')->nullable();
            $table->text('settings_stripe_currency')->nullable();
            $table->text('settings_stripe_display_name')->nullable();
            $table->text('settings_stripe_status')->nullable();
            $table->string('settings_subscriptions_prefix', 40)->nullable()->default('SUB-');
            $table->text('settings_paypal_email')->nullable();
            $table->text('settings_paypal_currency')->nullable();
            $table->text('settings_paypal_display_name')->nullable();
            $table->text('settings_paypal_mode')->nullable();
            $table->text('settings_paypal_status')->nullable();
            $table->text('settings_mollie_live_api_key')->nullable();
            $table->text('settings_mollie_test_api_key')->nullable();
            $table->text('settings_mollie_display_name')->nullable();
            $table->string('settings_mollie_mode', 40)->nullable()->default('live');
            $table->text('settings_mollie_currency')->nullable();
            $table->string('settings_mollie_status', 10)->nullable()->default('disabled');
            $table->text('settings_bank_details')->nullable();
            $table->text('settings_bank_display_name')->nullable();
            $table->text('settings_bank_status')->nullable();
            $table->text('settings_razorpay_keyid')->nullable();
            $table->text('settings_razorpay_secretkey')->nullable();
            $table->text('settings_razorpay_currency')->nullable();
            $table->text('settings_razorpay_display_name')->nullable();
            $table->string('settings_razorpay_status', 10)->nullable()->default('disabled');
            $table->string('settings_completed_check_email', 10)->nullable()->default('no');
            $table->string('settings_expenses_billable_by_default', 10)->nullable()->default('yes');
            $table->text('settings_tickets_edit_subject')->nullable();
            $table->text('settings_tickets_edit_body')->nullable();
            $table->string('settings_theme_name', 60)->nullable()->default('default');
            $table->text('settings_theme_head')->nullable();
            $table->text('settings_theme_body')->nullable();
            $table->text('settings_track_thankyou_session_id')->nullable();
            $table->string('settings_proposals_prefix', 30)->nullable()->default('PROP-');
            $table->string('settings_proposals_show_view_status', 10)->nullable()->default('yes');
            $table->string('settings_contracts_prefix', 30)->nullable()->default('CONT-');
            $table->string('settings_contracts_show_view_status', 10)->nullable()->default('yes');
            $table->string('settings_cronjob_has_run', 10)->nullable()->default('no');
            $table->timestamp('settings_cronjob_last_run')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('settings');
    }
};
