<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

return new class extends Migration
{
    /**
     * Run the migrations.
     */
    public function up(): void
    {
        Schema::create('leads', function (Blueprint $table) {
            $table->integer('lead_id')->primary();
            $table->string('lead_uniqueid', 100)->nullable();
            $table->string('lead_importid', 100)->nullable();
            $table->float('lead_position');
            $table->timestamp('lead_created')->nullable();
            $table->timestamp('lead_updated')->nullable();
            $table->timestamp('lead_date_status_change')->nullable();
            $table->integer('lead_creatorid')->nullable();
            $table->integer('lead_updatorid')->nullable();
            $table->integer('lead_categoryid')->nullable()->default(3);
            $table->string('lead_firstname', 100)->nullable();
            $table->string('lead_lastname', 100)->nullable();
            $table->string('lead_email', 150)->nullable();
            $table->string('lead_phone', 150)->nullable();
            $table->string('lead_job_position', 150)->nullable();
            $table->string('lead_company_name', 150)->nullable();
            $table->string('lead_website', 150)->nullable();
            $table->string('lead_street', 150)->nullable();
            $table->string('lead_city', 150)->nullable();
            $table->string('lead_state', 150)->nullable();
            $table->string('lead_zip', 150)->nullable();
            $table->string('lead_country', 150)->nullable();
            $table->string('lead_source', 150)->nullable();
            $table->string('lead_input_source', 20)->nullable()->default('app');
            $table->text('lead_input_ip_address')->nullable();
            $table->string('lead_title', 250)->nullable();
            $table->text('lead_description')->nullable();
            $table->decimal('lead_value', 10)->nullable();
            $table->date('lead_last_contacted')->nullable();
            $table->string('lead_converted', 10)->nullable()->default('no');
            $table->integer('lead_converted_by_userid')->nullable();
            $table->timestamp('lead_converted_date')->nullable();
            $table->integer('lead_converted_clientid')->nullable();
            $table->smallInteger('lead_status')->nullable()->default(1);
            $table->string('lead_active_state', 10)->nullable()->default('active');
            $table->string('lead_visibility', 40)->nullable()->default('visible');
            $table->string('lead_cover_image', 10)->nullable()->default('no');
            $table->text('lead_cover_image_uniqueid')->nullable();
            $table->text('lead_cover_image_filename')->nullable();
            $table->text('lead_custom_field_1')->nullable();
            $table->text('lead_custom_field_2')->nullable();
            $table->text('lead_custom_field_3')->nullable();
            $table->text('lead_custom_field_4')->nullable();
            $table->text('lead_custom_field_5')->nullable();
            $table->text('lead_custom_field_6')->nullable();
            $table->text('lead_custom_field_7')->nullable();
            $table->text('lead_custom_field_8')->nullable();
            $table->text('lead_custom_field_9')->nullable();
            $table->text('lead_custom_field_10')->nullable();
            $table->text('lead_custom_field_11')->nullable();
            $table->text('lead_custom_field_12')->nullable();
            $table->text('lead_custom_field_13')->nullable();
            $table->text('lead_custom_field_14')->nullable();
            $table->text('lead_custom_field_15')->nullable();
            $table->text('lead_custom_field_16')->nullable();
            $table->text('lead_custom_field_17')->nullable();
            $table->text('lead_custom_field_18')->nullable();
            $table->text('lead_custom_field_19')->nullable();
            $table->text('lead_custom_field_20')->nullable();
            $table->text('lead_custom_field_21')->nullable();
            $table->text('lead_custom_field_22')->nullable();
            $table->text('lead_custom_field_23')->nullable();
            $table->text('lead_custom_field_24')->nullable();
            $table->text('lead_custom_field_25')->nullable();
            $table->text('lead_custom_field_26')->nullable();
            $table->text('lead_custom_field_27')->nullable();
            $table->text('lead_custom_field_28')->nullable();
            $table->text('lead_custom_field_29')->nullable();
            $table->text('lead_custom_field_30')->nullable();
            $table->timestamp('lead_custom_field_31')->nullable();
            $table->timestamp('lead_custom_field_32')->nullable();
            $table->timestamp('lead_custom_field_33')->nullable();
            $table->timestamp('lead_custom_field_34')->nullable();
            $table->timestamp('lead_custom_field_35')->nullable();
            $table->timestamp('lead_custom_field_36')->nullable();
            $table->timestamp('lead_custom_field_37')->nullable();
            $table->timestamp('lead_custom_field_38')->nullable();
            $table->timestamp('lead_custom_field_39')->nullable();
            $table->timestamp('lead_custom_field_40')->nullable();
            $table->text('lead_custom_field_41')->nullable();
            $table->text('lead_custom_field_42')->nullable();
            $table->text('lead_custom_field_43')->nullable();
            $table->text('lead_custom_field_44')->nullable();
            $table->text('lead_custom_field_45')->nullable();
            $table->text('lead_custom_field_46')->nullable();
            $table->text('lead_custom_field_47')->nullable();
            $table->text('lead_custom_field_48')->nullable();
            $table->text('lead_custom_field_49')->nullable();
            $table->text('lead_custom_field_50')->nullable();
            $table->text('lead_custom_field_51')->nullable();
            $table->text('lead_custom_field_52')->nullable();
            $table->text('lead_custom_field_53')->nullable();
            $table->text('lead_custom_field_54')->nullable();
            $table->text('lead_custom_field_55')->nullable();
            $table->text('lead_custom_field_56')->nullable();
            $table->text('lead_custom_field_57')->nullable();
            $table->text('lead_custom_field_58')->nullable();
            $table->text('lead_custom_field_59')->nullable();
            $table->text('lead_custom_field_60')->nullable();
            $table->text('lead_custom_field_61')->nullable();
            $table->text('lead_custom_field_62')->nullable();
            $table->text('lead_custom_field_63')->nullable();
            $table->text('lead_custom_field_64')->nullable();
            $table->text('lead_custom_field_65')->nullable();
            $table->text('lead_custom_field_66')->nullable();
            $table->text('lead_custom_field_67')->nullable();
            $table->text('lead_custom_field_68')->nullable();
            $table->text('lead_custom_field_69')->nullable();
            $table->text('lead_custom_field_70')->nullable();
            $table->text('lead_custom_field_71')->nullable();
            $table->text('lead_custom_field_72')->nullable();
            $table->text('lead_custom_field_73')->nullable();
            $table->text('lead_custom_field_74')->nullable();
            $table->text('lead_custom_field_75')->nullable();
            $table->text('lead_custom_field_76')->nullable();
            $table->text('lead_custom_field_77')->nullable();
            $table->text('lead_custom_field_78')->nullable();
            $table->text('lead_custom_field_79')->nullable();
            $table->text('lead_custom_field_80')->nullable();
            $table->text('lead_custom_field_81')->nullable();
            $table->text('lead_custom_field_82')->nullable();
            $table->text('lead_custom_field_83')->nullable();
            $table->text('lead_custom_field_84')->nullable();
            $table->text('lead_custom_field_85')->nullable();
            $table->text('lead_custom_field_86')->nullable();
            $table->text('lead_custom_field_87')->nullable();
            $table->text('lead_custom_field_88')->nullable();
            $table->text('lead_custom_field_89')->nullable();
            $table->text('lead_custom_field_90')->nullable();
            $table->text('lead_custom_field_91')->nullable();
            $table->text('lead_custom_field_92')->nullable();
            $table->text('lead_custom_field_93')->nullable();
            $table->text('lead_custom_field_94')->nullable();
            $table->text('lead_custom_field_95')->nullable();
            $table->text('lead_custom_field_96')->nullable();
            $table->text('lead_custom_field_97')->nullable();
            $table->text('lead_custom_field_98')->nullable();
            $table->text('lead_custom_field_99')->nullable();
            $table->text('lead_custom_field_100')->nullable();
            $table->text('lead_custom_field_101')->nullable();
            $table->text('lead_custom_field_102')->nullable();
            $table->text('lead_custom_field_103')->nullable();
            $table->text('lead_custom_field_104')->nullable();
            $table->text('lead_custom_field_105')->nullable();
            $table->text('lead_custom_field_106')->nullable();
            $table->text('lead_custom_field_107')->nullable();
            $table->text('lead_custom_field_108')->nullable();
            $table->text('lead_custom_field_109')->nullable();
            $table->text('lead_custom_field_110')->nullable();
            $table->integer('lead_custom_field_111')->nullable();
            $table->integer('lead_custom_field_112')->nullable();
            $table->integer('lead_custom_field_113')->nullable();
            $table->integer('lead_custom_field_114')->nullable();
            $table->integer('lead_custom_field_115')->nullable();
            $table->integer('lead_custom_field_116')->nullable();
            $table->integer('lead_custom_field_117')->nullable();
            $table->integer('lead_custom_field_118')->nullable();
            $table->integer('lead_custom_field_119')->nullable();
            $table->integer('lead_custom_field_120')->nullable();
            $table->integer('lead_custom_field_121')->nullable();
            $table->integer('lead_custom_field_122')->nullable();
            $table->integer('lead_custom_field_123')->nullable();
            $table->integer('lead_custom_field_124')->nullable();
            $table->integer('lead_custom_field_125')->nullable();
            $table->integer('lead_custom_field_126')->nullable();
            $table->integer('lead_custom_field_127')->nullable();
            $table->integer('lead_custom_field_128')->nullable();
            $table->integer('lead_custom_field_129')->nullable();
            $table->integer('lead_custom_field_130')->nullable();
            $table->decimal('lead_custom_field_131', 10)->nullable();
            $table->decimal('lead_custom_field_132', 10)->nullable();
            $table->decimal('lead_custom_field_133', 10)->nullable();
            $table->decimal('lead_custom_field_134', 10)->nullable();
            $table->decimal('lead_custom_field_135', 10)->nullable();
            $table->decimal('lead_custom_field_136', 10)->nullable();
            $table->decimal('lead_custom_field_137', 10)->nullable();
            $table->decimal('lead_custom_field_138', 10)->nullable();
            $table->decimal('lead_custom_field_139', 10)->nullable();
            $table->decimal('lead_custom_field_140', 10)->nullable();
            $table->decimal('lead_custom_field_141', 10)->nullable();
            $table->decimal('lead_custom_field_142', 10)->nullable();
            $table->decimal('lead_custom_field_143', 10)->nullable();
            $table->decimal('lead_custom_field_144', 10)->nullable();
            $table->decimal('lead_custom_field_145', 10)->nullable();
            $table->decimal('lead_custom_field_146', 10)->nullable();
            $table->decimal('lead_custom_field_147', 10)->nullable();
            $table->decimal('lead_custom_field_148', 10)->nullable();
            $table->decimal('lead_custom_field_149', 10)->nullable();
            $table->decimal('lead_custom_field_150', 10)->nullable();
            $table->text('leadresource_type')->nullable();
            $table->integer('leadresource_id')->nullable();
            $table->text('lead_mapping_type')->nullable();
            $table->integer('lead_mapping_id')->nullable();
        });
    }

    /**
     * Reverse the migrations.
     */
    public function down(): void
    {
        Schema::dropIfExists('leads');
    }
};
